blueprintapp/blueprints/people/models.py
from blueprintapp.app import db
from flask_login import UserMixin

class Person(db.Model, UserMixin):
    __tablename__ = 'people'

    pid = db.Column(db.Integer, primary_key = True)
    email = db.Column(db.String, nullable = False)
    password = db.Column(db.String, nullable = False)
    name = db.Column(db.String, nullable = False)
    lastName = db.Column(db.String, nullable = False)

    def __repr__(self):
        return f'<PERSON {self.name} {self.lastName}>'
    
    def get_id(self):
        return self.pid
    
    def get_email(self):
        return self.email

blueprintapp/blueprints/people/routes.py
from flask import request, render_template, redirect, url_for, Blueprint
from flask_login import login_user, logout_user, current_user
from blueprintapp.app import db
from blueprintapp.blueprints.people.models import Person
from flask_bcrypt import Bcrypt, generate_password_hash

people = Blueprint('people', __name__, template_folder='templates', static_folder="static")
bcrypt = Bcrypt()

@people.route('/', methods =['GET', 'POST'])
def index():
    if request.method == 'GET':
        return render_template('people/index.html')
    elif request.method == 'POST':
        email = request.form['email']
        password = request.form['password']

        user = Person.query.filter_by(email = email).first()
        if bcrypt.check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('todos.index'))
        else: 
            return render_template('people/index.html', message='Credenciales invalidas')

@people.route('/create', methods = ['GET', 'POST'])
def create():
    if request.method == 'GET':
        return render_template('people/create.html')
    elif request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        name = request.form['name']
        lastName = request.form['lastName']
        hash_password = bcrypt.generate_password_hash(password).decode('utf-8')

        people = Person(email = email, password = hash_password, name = name, lastName = lastName)

        db.session.add(people)
        db.session.commit()

        return redirect(url_for('people.index'))

@people.route('logout')
def logout():
    logout_user()
    return redirect(url_for('people.index'))

blueprintapp/blueprints/people/templates/people/create.html
{% extends 'base.html' %}
{% block title %} People {% endblock %}

{% block content %}
    <form action="" method="post" class="people-form">
        <h1>Sign Up</h1>
        <input type="email" placeholder="Email" name="email">
        <input type="password" placeholder="Password" name="password">
        <input type="text" placeholder="Name" name="name">
        <input type="text" placeholder="Last name" name="lastName">
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{{url_for('people.index')}}">You have an account?</a>
    </form>
{% endblock %}

blueprintapp/blueprints/people/templates/people/index.html
{% extends 'base.html' %}
{% block title %} People {% endblock %}

{% block content %}
    <form action="" method="post" class="people-form">
        <p class="alert-message">{{message}}</p>
        <h1>Sign in</h1>
        <input type="email" placeholder="Email" name="email">
        <input type="password" placeholder="Password" name="password">
        <button type="submit" class="btn btn-primary">Submit</button>
        <a href="{{url_for('people.create')}}">You don´t have an account?</a>
    </form>
{% endblock %}