blueprintapp/blueprints/todos/models.py
from blueprintapp.app import db
from sqlalchemy.orm import relationship
from sqlalchemy.orm import backref
from blueprintapp.blueprints.people.models import Person

class Topic(db.Model):
    __tablename__ = 'topic'
    topId = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String, nullable=False)
    pid = db.Column(db.Integer, db.ForeignKey('people.pid', name='fk_topic_pid'), nullable=False)
    fk_topic_pid = relationship(Person, backref=backref("children_topic_pid", cascade="all,delete"))

    def __repr__(self):
        return f'<TOPIC {self.name}>'
    
    def get_id(self):
        return self.topId

class Todo(db.Model):
    __tablename__ = 'todos'

    tid = db.Column(db.Integer, primary_key=True)
    description = db.Column(db.String, nullable=False)
    done = db.Column(db.Boolean)
    topId = db.Column(db.Integer, db.ForeignKey('topic.topId', name='fk_todo_topid'), nullable=False)  # Nombre de la clave foránea
    fk_topid = relationship(Topic, backref=backref("children", cascade="all,delete"))

    def __repr__(self):
        return f'<TODO {self.description}, Done: {self.done}>'
    
    def get_id(self):
        return self.tid
    
class Task(db.Model):
    __tablename__ = 'tasks'

    taskId = db.Column(db.Integer, primary_key=True)
    tittle = db.Column(db.String, nullable=False)
    taskContent = db.Column(db.String, nullable=False)
    pid = db.Column(db.Integer, db.ForeignKey('people.pid', name='fk_task_pid'), nullable=False)  # Nombre de la clave foránea
    fk_task_pid = relationship(Person, backref=backref("children_task_pid", cascade="all,delete"))

    def __repr__(self):
        return f'<TASK {self.tittle}, CONTENT: {self.taskContent}>'
    
    def get_id(self):
        return self.taskId

blueprintapp/blueprints/todos/routes.py
from flask import request, render_template, redirect, url_for, Blueprint, jsonify
from flask_login import current_user

from blueprintapp.app import db
from blueprintapp.blueprints.todos.models import Todo, Topic, Task

todos = Blueprint('todos', __name__, template_folder='templates')


@todos.route('/')
def index():
    userId = current_user.pid

    topics = Topic.query.filter(Topic.pid == userId).all()
    topId = Topic.topId

    todos = Todo.query.filter(Todo.topId == topId).all()

    tasks = Task.query.filter(Task.pid == userId).all()
    return render_template('todos/index.html', topics = topics, todos = todos, tasks = tasks)

@todos.route('/create_todo', methods = ['POST'])
def create_todo():
    description = request.form['description']
    topid = request.form['topid']

    todo = Todo(description = description, topId = topid)
    db.session.add(todo)
    db.session.commit()
    return redirect(url_for('todos.index'))

@todos.route('/update_todo/<int:tid>', methods = ['PATCH'])
def update_todo(tid):
    # Obtener el todo a modificar
    todo = Todo.query.filter(Todo.tid == tid).first()

    if not todo:
        return jsonify({"error": "El todo no existe."}), 404

    # Obtener los datos enviados en la solicitud
    data = request.get_json()

    # Actualizar el campo 'description' si está presente en los datos
    if 'description' in data:
        todo.description = data['description']

    # Guardar los cambios en la base de datos
    db.session.commit()

    return jsonify({"message": "Todo actualizado correctamente.", "todo": {"tid": todo.tid, "description": todo.description}}), 200


@todos.route('/toggle_done/<int:tid>', methods=['PATCH'])
def toggle_done(tid):
    # Obtener el todo a modificar
    todo = Todo.query.filter(Todo.tid == tid).first()

    if not todo:
        return jsonify({"error": "El todo no existe."}), 404

    # Obtener los datos enviados en la solicitud
    data = request.get_json()

    # Actualizar el campo 'done' si está presente en los datos
    if 'done' in data:
        todo.done = data['done']

    # Guardar los cambios en la base de datos
    db.session.commit()

    return jsonify({"message": "Estado 'done' actualizado correctamente.", "todo": {"tid": todo.tid, "done": todo.done}}), 200

@todos.route('/delete_todo/<int:tid>', methods = ['DELETE'])
def delete_todo(tid):
    todo = Todo.query.filter(Todo.tid == tid).first()

    if todo:
        db.session.delete(todo)
        db.session.commit()
        return jsonify({"message": "Item eliminado correctamente."}), 200
    else:
        return jsonify({"error": "El item no existe."}), 404

@todos.route('/create_topic', methods = ['POST'])
def create_topic():
    name = request.form['name']
    pid = current_user.pid

    topic = Topic(name = name, pid = pid)

    db.session.add(topic)
    db.session.commit()
    return redirect(url_for('todos.index'))

@todos.route('/update_topic/<int:topid>', methods = ['PATCH'])
def update_topic(topid):
    topic = Topic.query.filter(Topic.topId == topid).first()

    if topic:
        data = request.get_json()

    # Actualizar el campo 'description' si está presente en los datos
    if 'name' in data:
        topic.name = data['name']

    # Guardar los cambios en la base de datos
    db.session.commit()

    return jsonify({"message": "Topic actualizado correctamente.", "todo": {"tid": topic.topId, "nombre": topic.name}}), 200
    
@todos.route('/del_top/<int:topId>', methods = ['DELETE'])
def del_top(topId):
    topic = Topic.query.filter(Topic.topId == topId).first()

    if topic:
        db.session.delete(topic)
        db.session.commit()
        return jsonify({"message": "Tema eliminado correctamente."}), 200
    else:
        return jsonify({"error": "El tema no existe."}), 404
    
@todos.route('/delete_task/<int:taskId>', methods = ['DELETE'])
def delete_task(taskId):
    task = Task.query.filter(Task.taskId == taskId).first()

    if task:
        db.session.delete(task)
        db.session.commit()
        return jsonify({"message": "Task delete"}), 200
    else :
        return jsonify({"message": "There was an error deleting the task"}), 404
    
@todos.route('/update_title/<int:taskId>', methods = ['PATCH'])
def update_title(taskId):
    task = Task.query.filter(Task.taskId == taskId).first()

    if task:
        data = request.get_json()

    # Actualizar el campo 'description' si está presente en los datos
    if 'title' in data:
        task.tittle = data['title']

    # Guardar los cambios en la base de datos
    db.session.commit()

    return jsonify({"message": "Task actualizada correctamente.", "todo": {"tid": task.taskId, "nombre": task.tittle}}), 200

@todos.route('/update_content/<int:taskId>', methods = ['PATCH'])
def update_content(taskId):
    task = Task.query.filter(Task.taskId == taskId).first()

    if task:
        data = request.get_json()

    # Actualizar el campo 'description' si está presente en los datos
    if 'content' in data:
        task.taskContent = data['content']

    # Guardar los cambios en la base de datos
    db.session.commit()

    return jsonify({"message": "Task actualizada correctamente.", "todo": {"tid": task.taskId, "contenido": task.taskContent}}), 200

blueprintapp/blueprints/todos/templates/todos/create.html
{% extends 'base.html' %}
{% block title %} Todos {% endblock %}

{% block content %}
    <h1>Create todo</h1>

    <form action="{{url_for('todos.create')}}" method="post">
        <input type="text" name="title" placeholder="Title" required="required">
        <input type="text" name="description" placeholder="Description">
        <input type="checkbox" name="done"> Done
        <input type="submit" value="create">
    </form>
{% endblock %}

blueprintapp/blueprints/todos/templates/todos/index.html
{% extends 'base.html' %}
{% block title %} To dos {% endblock %}

{% block content %}
    <header class="todos-header">
        <nav class="todos-nav">
                <div class="logo">
                    <a href="{{url_for('todos.index')}}" class="nav-link">
                        <img src="../../../../img/to-do-list.png" alt="Todo logo" class="img-logo">
                    </a>
                    <h1>Hello, {{current_user.name}} {{current_user.lastName}}</h1>
                </div>
                <div class="toggle-menu">
                    <i class="fa-solid fa-bars" onclick=showSidebar()></i>
                </div>
                <ul class="sidebar">
                    <li onclick=hideSidebar()><i class="fa-solid fa-xmark"></i></li>
                    <li class="nav-item"><a href="#" class="nav-link" data-bs-toggle="modal" data-bs-target="#editModal">Create list</a></li>
                    <li class="nav-item"><a href="#" class="nav-link" data-bs-toggle="modal" data-bs-target="#taskModal">Create task</a></li>
                    <li class="nav-item"><a href="{{url_for('people.logout')}}" class="nav-link">Log out</a></li>
                    <li class="side-item switch switch__mobile">
                        <a class="btn nav-boton mr-2" id="darkModeToggle_mobile" role="button">
                            <i class="fas mb-2 mr-1 fa-moon theme-icon"></i>
                        </a>
                    </li>
                    <li class="nav-item"><a href="#" class="nav-link">
                        <div class="user_container user-container-mobile">{{current_user.name[0]}}</div>
                    </a></li>
                </ul>
            <ul class="nav-list">
                <li class="nav-item"><a href="#" class="nav-link" data-bs-toggle="modal" data-bs-target="#editModal">Create list</a></li>
                <li class="nav-item"><a href="#" class="nav-link" data-bs-toggle="modal" data-bs-target="#taskModal">Create task</a></li>
                <li class="nav-item switch">
                    <a class="toggle-theme" id="darkModeToggle" role="button">
                        <i class="fas mb-2 mr-1 fa-moon theme-icon"></i>
                    </a>
                <li class="nav-item"><a href="{{url_for('people.logout')}}" class="nav-link">Log out</a></li>
                <li class="nav-item"><a href="#" class="nav-link">
                    <div class="user_container">{{current_user.name[0]}}</div>
                </a></li>
            </ul>
        </nav>
    </header>

    <div class="main-wrapper">
            {% for topic in topics%}
                <div class="todo__container" id="todo-list">
                    <div class="topic__container">
                        <input type="text" name="topic" class="list-input topic-input" value="{{topic.name}}" id="topic-name-{{topic.topId}}" onchange="update_topic({{topic.topId}}) ">
                    </div>
                    {% for todo in todos %}
                        {% if topic.topId == todo.topId %}
                            <div class="modify-form">
                                <div class="list__container">
                                    <input type="checkbox" class="checkbox" name="done" id="done-checkbox-{{ todo.tid }}"
                                    {% if todo.done %}checked{% endif %}
                                    onchange="toggleDone({{ todo.tid }})">
                                    <input type="text" name="todo" class="list-input" value="{{todo.description}}" id="description-input-{{ todo.tid }}" onchange="update_todo({{ todo.tid }})">
                                    <button class="delete-btn" onclick="delete_todo({{todo.tid}})">
                                        <i class="fa-solid fa-xmark"></i>
                                    </button>
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="todo-options__container">
                        <form action="{{url_for('todos.create_todo')}}" class="newTodo-form" id="newTodo-form" method="post">
                            <input type="text" placeholder="Add a new Todo!!" name="description">
                            <input type="hidden" name="topid" value="{{topic.topId}}">
                            <button type="submit" class="btn btn-primary">Save</button>
                        </form>


                        <div class="todo-options">
                            <button type="button" class="trash-btn" onclick="del_top({{ topic.topId }})">
                                <i class="fa-solid fa-trash"></i>
                            </button>
                        </div>

                    </div>
                </div>
            {% endfor %}

            {% for task in tasks %}
                <div class="task__container">
                    <div>
                        <input type="text" value="{{task.tittle}}" class="list-input topic-input" id="task-title-{{task.taskId}}" onchange="update_title({{task.taskId}})">
                    </div>
                    <div class="task-body">
                        <input type="text" value="{{task.taskContent}}" class="list-input task-input__content" id="task-content-{{task.taskId}}" onchange="update_content({{task.taskId}})">
                    </div>
                    <div class="task__footer">
                        <input type="hidden" value="{{task.taskId}}">
                        <button class="btn btn-danger" onclick="delete_task({{task.taskId}})">Delete</button>
                    </div>
                </div>
            {% endfor %}
    </div>

    <!-- Modal Create list-->
<div class="modal fade" id="editModal" tabindex="-1" aria-labelledby="editModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="editModalLabel">New Topic!!</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{{url_for('todos.create_topic')}}" method="post">
            <div class="modal-body">
                <input type="text" placeholder="Topic name" name="name">
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
      </div>
    </div>
  </div>
     <!-- Modal Create task-->
<div class="modal fade" id="taskModal" tabindex="-1" aria-labelledby="taskModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="taskModalLabel">New Topic!!</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <form action="{{url_for('todos.create_topic')}}" method="post">
            <div class="modal-body">
                <input type="text" placeholder="Task name" name="name">
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Save changes</button>
            </div>
        </form>
      </div>
    </div>
  </div>
    <script src="../../../../js/script.js"></script>
    <script src="../../../../js/darkMode.js"></script>
  
{% endblock %}